version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.7.1
    steps:
      - checkout
      - run: rm -f Gemfile.lock && bundle install
      - run: rake update_measures
      - run: rake test:regenerate_osms
      - run: rake test:all
      - store_test_results:
          path: test/reports/
